import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const artifacts = [
  {
    claim: "identity_age_days",
    circuit: "circuits/identity_age_threshold.circom",
    r1cs: "circuits/build/identity_age_threshold.r1cs",
    wasm: "circuits/build/identity_age_threshold_js/identity_age_threshold.wasm",
    zkey: "circuits/build/identity_age_threshold.zkey",
    verification_key: "circuits/build/identity_age_threshold.vkey.json"
  },
  {
    claim: "reciprocal_receipt_count",
    circuit: "circuits/reciprocal_receipt_count_threshold.circom",
    r1cs: "circuits/build/reciprocal_receipt_count_threshold.r1cs",
    wasm: "circuits/build/reciprocal_receipt_count_threshold_js/reciprocal_receipt_count_threshold.wasm",
    zkey: "circuits/build/reciprocal_receipt_count_threshold.zkey",
    verification_key: "circuits/build/reciprocal_receipt_count_threshold.vkey.json"
  }
];

function sha256(path: string): string | null {
  if (!existsSync(path)) return null;
  return `0x${createHash("sha256").update(readFileSync(path)).digest("hex")}`;
}

const manifest = {
  type: "tsl.zk.release_manifest.v1",
  generated_at: new Date().toISOString(),
  ceremony_warning: "Development-only Groth16 setup generated by local snarkjs powers-of-tau contribution. Do not treat these zkeys as production trusted setup artifacts.",
  artifacts: artifacts.map((artifact) => ({
    claim: artifact.claim,
    circuit: artifact.circuit,
    circuit_hash: sha256(artifact.circuit),
    r1cs: artifact.r1cs,
    r1cs_hash: sha256(artifact.r1cs),
    wasm: artifact.wasm,
    wasm_hash: sha256(artifact.wasm),
    zkey: artifact.zkey,
    zkey_hash: sha256(artifact.zkey),
    verification_key: artifact.verification_key,
    verification_key_hash: sha256(artifact.verification_key)
  }))
};

const out = process.env.TSL_ZK_MANIFEST_OUT ?? "reports/zk-artifact-manifest.json";
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `${JSON.stringify(manifest, null, 2)}\n`);
process.stdout.write(`${JSON.stringify(manifest, null, 2)}\n`);
