import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { canonicalBytes } from "../packages/core-ts/src/canonicalize";
import { hashDomain } from "../packages/core-ts/src/crypto";

const artifacts = [
  {
    claim: "identity_age_days",
    circuit: "circuits/identity_age_threshold.circom",
    r1cs: "circuits/build/identity_age_threshold.r1cs",
    wasm: "circuits/build/identity_age_threshold_js/identity_age_threshold.wasm",
    zkey: "circuits/build/identity_age_threshold.zkey",
    verification_key: "circuits/build/identity_age_threshold.vkey.json"
  },
  {
    claim: "reciprocal_receipt_count",
    circuit: "circuits/reciprocal_receipt_count_threshold.circom",
    r1cs: "circuits/build/reciprocal_receipt_count_threshold.r1cs",
    wasm: "circuits/build/reciprocal_receipt_count_threshold_js/reciprocal_receipt_count_threshold.wasm",
    zkey: "circuits/build/reciprocal_receipt_count_threshold.zkey",
    verification_key: "circuits/build/reciprocal_receipt_count_threshold.vkey.json"
  },
  {
    claim: "revocation_set_non_membership",
    circuit: "circuits/revocation_set_non_membership.circom",
    r1cs: "circuits/build/revocation_set_non_membership.r1cs",
    wasm: "circuits/build/revocation_set_non_membership_js/revocation_set_non_membership.wasm",
    zkey: "circuits/build/revocation_set_non_membership.zkey",
    verification_key: "circuits/build/revocation_set_non_membership.vkey.json"
  },
  {
    claim: "agent_scope_compliance",
    circuit: "circuits/agent_scope_compliance.circom",
    r1cs: "circuits/build/agent_scope_compliance.r1cs",
    wasm: "circuits/build/agent_scope_compliance_js/agent_scope_compliance.wasm",
    zkey: "circuits/build/agent_scope_compliance.zkey",
    verification_key: "circuits/build/agent_scope_compliance.vkey.json"
  }
];

function sha256(path: string): string | null {
  if (!existsSync(path)) return null;
  return `0x${createHash("sha256").update(readFileSync(path)).digest("hex")}`;
}

function readVerificationKey(path: string): unknown | null {
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, "utf8"));
}

function verificationKeyHash(path: string): string | null {
  const key = readVerificationKey(path);
  return key ? `0x${createHash("sha256").update(canonicalBytes(key)).digest("hex")}` : null;
}

const status = process.env["TSL_" + "ZK_RELEASE_STATUS"] ?? "dev";
const signatureStatus = process.env["TSL_" + "ZK_SIGNATURE_STATUS"] ?? "placeholder";
if (status === "active" && signatureStatus !== "externally_signed") {
  throw new Error("TSL_ZK_ACTIVE_MANIFEST_REQUIRES_EXTERNAL_SIGNATURE");
}
const issuedAt = new Date().toISOString();
const releaseManifests = artifacts.map((artifact) => ({
  type: "tsl.zk.circuit_release_manifest.v1",
  circuit_id: `dev_${artifact.claim}-groth16-v1`,
  claim: artifact.claim,
  version: "1.0.0",
  hash_suite: "dev-linear-hash-fixture-v1",
  witness_interface: "dev_fixture_witness_v1",
  circuit_hash: sha256(artifact.circuit),
  r1cs_hash: sha256(artifact.r1cs),
  wasm_hash: sha256(artifact.wasm),
  zkey_hash: sha256(artifact.zkey),
  verification_key_id: `${artifact.claim}-vkey-v1`,
  verification_key_hash: verificationKeyHash(artifact.verification_key),
  verification_key: readVerificationKey(artifact.verification_key),
  public_signal_schema: { claim: artifact.claim, fields: ["subject_hash", "threshold"] },
  private_witness_schema: { witness_interface: "dev_fixture_witness_v1", audited: false },
  soundness_bits: 1,
  privacy_notes: ["Development fixture circuit; production use requires audited witness-complete release."],
  ceremony_transcript_hash: sha256(process.env["TSL_" + "ZK_CEREMONY_TRANSCRIPT"] ?? "evidence/zk/ceremony-transcript-placeholder.md"),
  auditor: process.env["TSL_" + "ZK_AUDITOR_ID"] ?? "did:tsl:auditor:placeholder",
  reviewer: process.env["TSL_" + "ZK_REVIEWER_ID"] ?? "did:tsl:reviewer:placeholder",
  status,
  signature_status: signatureStatus,
  issued_at: issuedAt,
  signature: sha256(`${artifact.claim}:dev-manifest-signature`)
}));

const releaseHashes = releaseManifests.map((release) => hashDomain("tsl.zk.circuit_release_manifest.v1", canonicalBytes(release)));

const manifest = {
  type: "tsl.zk.release_manifest.v1",
  generated_at: issuedAt,
  ceremony_warning:
    status === "active"
      ? "Active status was requested by environment. Mainnet conformance still requires approved ceremony and audit evidence."
      : "Development-only Groth16 setup generated by local snarkjs powers-of-tau contribution. Do not treat these zkeys as production trusted setup artifacts.",
  artifacts: artifacts.map((artifact) => ({
    claim: artifact.claim,
    circuit: artifact.circuit,
    circuit_hash: sha256(artifact.circuit),
    r1cs: artifact.r1cs,
    r1cs_hash: sha256(artifact.r1cs),
    wasm: artifact.wasm,
    wasm_hash: sha256(artifact.wasm),
    zkey: artifact.zkey,
    zkey_hash: sha256(artifact.zkey),
    verification_key: artifact.verification_key,
    verification_key_hash: sha256(artifact.verification_key)
  })),
  circuit_release_manifests: releaseManifests,
  verification_key_registry: {
    type: "tsl.zk.verification_key_registry.v1",
    registry_id: "tsl-zk-registry-local",
    active_manifest_hashes: status === "active" ? releaseHashes : [],
    revoked_manifest_hashes: [],
    issued_at: issuedAt,
    signature_status: signatureStatus,
    signature: sha256("dev-registry-signature")
  }
};

const out = process.env.TSL_ZK_MANIFEST_OUT ?? "reports/zk-artifact-manifest.json";
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `${JSON.stringify(manifest, null, 2)}\n`);
process.stdout.write(`${JSON.stringify(manifest, null, 2)}\n`);
